sudo: required
services: 
    - docker

before_install:
    - docker build -t outmanebaladi/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true outmanebaladi/docker-react npm run test 
